baseurl: /yumi2000@github.com

markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: yumi
url: http://yumi2000.github.io
description: IN GOD WE TRUST 
github: yumi2000
gravatar_url: http://img3.douban.com/icon/ul2352991-3.jpg

